apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mari-app-ingress
  namespace: ingress-nginx  # Certifique-se de que isso est√° correto
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: desafiojackexpertsmari.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mari-app
                port:
                  number: 3001  
